artifactory:
  replicaCount: 2
  persistence:
    size: 10Gi
  service:
    type: ClusterIP

postgresql:
  enabled: true
  primary:
    persistence:
      size: 5Gi

nginx:
  enabled: true
  service:
    type: ClusterIP