artifactory:
  replicaCount: 1
  persistence:
    size: 50Gi
  service:
    type: ClusterIP

postgresql:
  enabled: true
  postgresqlPassword: "artifactory123"
  persistence:
    size: 20Gi

nginx:
  enabled: true
  service:
    type: ClusterIP
