---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jfrog
spec:
  interval: 24h
  url: https://charts.jfrog.io
  insecure: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: artifactory
spec:
  targetNamespace: artifactory
  releaseName: artifactory
  interval: 30m
  chart:
    spec:
      chart: artifactory
      version: "107.x"
      sourceRef:
        kind: HelmRepository
        name: jfrog
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: jfrog-values
      valuesKey: values.yaml
