artifactory:
  replicaCount: 2
  persistence:
    size: 20Gi
  service:
    type: ClusterIP

postgresql:
  enabled: true
  postgresqlPassword: "artifactory123"
  persistence:
    size: 10Gi

nginx:
  enabled: true
  service:
    type: ClusterIP
