# Lightweight kube-prometheus-stack configuration for Production Cluster
# This configuration disables components that are centralized in the hub cluster

# Disable Grafana - centralized in hub cluster
grafana:
  enabled: false

# Disable AlertManager - centralized in hub cluster  
alertmanager:
  enabled: false

# Configure Prometheus with minimal resources and remote write
prometheus:
  prometheusSpec:
    # Minimal retention since metrics are sent to hub
    retention: "2h"
    retentionSize: "1GB"
    
    # Reduced resource allocation
    resources:
      requests:
        memory: "400Mi"
        cpu: "100m"
      limits:
        memory: "800Mi" 
        cpu: "200m"
    
    # Storage configuration
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 2Gi
    
    # Remote write configuration to hub cluster
    remoteWrite:
      - url: "http://YOUR-HUB-PROMETHEUS-ENDPOINT:9090/api/v1/write"
        writeRelabelConfigs:
          # Add cluster label to identify metrics source
          - targetLabel: cluster
            replacement: "production"
          # Add origin prometheus label
          - targetLabel: origin_prometheus
            replacement: "production-prometheus"
        queueConfig:
          capacity: 10000
          maxShards: 50
          maxSamplesPerSend: 2000
          batchSendDeadline: 5s
          minBackoff: 30ms
          maxBackoff: 100ms
    
    # Minimal external labels
    externalLabels:
      cluster: "production"
      environment: "production"

# Keep kube-state-metrics for cluster-specific metrics
kube-state-metrics:
  enabled: true
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"

# Keep node-exporter for node metrics
nodeExporter:
  enabled: true
  resources:
    requests:
      memory: "64Mi"
      cpu: "25m"
    limits:
      memory: "128Mi"
      cpu: "50m"

# Simplified Prometheus Operator configuration
prometheusOperator:
  # Disable admission webhooks for simplicity
  admissionWebhooks:
    enabled: false
  
  # Disable TLS for internal communication
  tls:
    enabled: false
    
  # Reduced resource allocation
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"

# Configure scrape configs for production-specific monitoring
additionalPrometheusRules:
  - name: production-specific-rules
    groups:
      - name: production.rules
        rules:
          # Add production-specific recording rules here
          - record: cluster:up:sum
            expr: sum(up{cluster="production"})
