apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-prometheus-federation
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/component: monitoring
data:
  additional-scrape-configs.yaml: |
    # Production cluster federation
    - job_name: 'federate-production'
      honor_labels: true
      scrape_interval: 30s
      scrape_timeout: 15s
      metrics_path: '/federate'
      params:
        'match[]':
          # Core Kubernetes metrics
          - '{job="apiserver"}'
          - '{job="kube-state-metrics"}'
          - '{job="kubelet"}'
          - '{job="node-exporter"}'
          - '{job="cadvisor"}'
          # Flux controller metrics
          - '{job="flux-system"}'
          - '{__name__=~"gotk_.*"}'
          - '{__name__=~"controller_runtime_.*"}'
          # Application metrics
          - '{__name__=~"up|.*_total|.*_duration_.*|.*_info"}'
      static_configs:
        - targets:
            # These targets will be automatically discovered when Prometheus services are available
            # Format: service-name.namespace.svc.cluster.local:port
            - 'kube-prometheus-stack-prometheus.production.svc.cluster.local:9090'
            - 'prometheus-operated.production.svc.cluster.local:9090'
      relabel_configs:
        - target_label: cluster
          replacement: 'production'
        - source_labels: [__address__]
          target_label: __address__
          regex: '(.*)'
          replacement: '${1}'
    
    # Staging cluster federation  
    - job_name: 'federate-staging'
      honor_labels: true
      scrape_interval: 30s
      scrape_timeout: 15s
      metrics_path: '/federate'
      params:
        'match[]':
          # Core Kubernetes metrics
          - '{job="apiserver"}'
          - '{job="kube-state-metrics"}'
          - '{job="kubelet"}'
          - '{job="node-exporter"}'
          - '{job="cadvisor"}'
          # Flux controller metrics
          - '{job="flux-system"}'
          - '{__name__=~"gotk_.*"}'
          - '{__name__=~"controller_runtime_.*"}'
          # Application metrics
          - '{__name__=~"up|.*_total|.*_duration_.*|.*_info"}'
      static_configs:
        - targets:
            # These targets will be automatically discovered when Prometheus services are available
            # Format: service-name.namespace.svc.cluster.local:port
            - 'kube-prometheus-stack-prometheus.staging.svc.cluster.local:9090'
            - 'prometheus-operated.staging.svc.cluster.local:9090'
      relabel_configs:
        - target_label: cluster
          replacement: 'staging'
        - source_labels: [__address__]
          target_label: __address__
          regex: '(.*)'
          replacement: '${1}'
