---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-remote-write
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/component: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-remote-write
  labels:
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/component: monitoring
rules:
  # Basic permissions for Prometheus remote write receiver
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list", "watch"]
  # Access to monitoring resources
  - apiGroups: ["monitoring.coreos.com"]
    resources: ["servicemonitors", "podmonitors", "prometheusrules"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-remote-write
  labels:
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/component: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-remote-write
subjects:
  - kind: ServiceAccount
    name: prometheus-remote-write
    namespace: monitoring
