artifactory:
  replicaCount: 1
  persistence:
    size: 10Gi
  service:
    type: ClusterIP

postgresql:
  enabled: true
  persistence:
    size: 5Gi

nginx:
  enabled: true
  service:
    type: ClusterIP