artifactory:
  replicaCount: 1
  persistence:
    size: 10Gi
  service:
    type: ClusterIP

postgresql:
  auth:
    password: jfrog1234
  image:
    tag: postgresql:16.6.0-debian-12-r2
  enabled: true
  primary:
    persistence:
      size: 5Gi

nginx:
  enabled: true
  service:
    type: ClusterIP