apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: artifactory
spec:
  chart:
    spec:
      version: "107.x"
  test:
    enable: false
  values:
    artifactory:
      replicaCount: 1
      persistence:
        size: 20Gi
      service:
        type: ClusterIP

    postgresql:
      enabled: true
      postgresqlPassword: "artifactory123"
      persistence:
        size: 10Gi

    nginx:
      enabled: true
      service:
        type: ClusterIP
