apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: artifactory
spec:
  chart:
    spec:
      chart: jfrog-platform
      sourceRef:
        kind: HelmRepository
        name: jfrog
      interval: 12h
      version: "11.2.1"
  test:
    enable: false
  valuesFrom:
    - kind: ConfigMap
      name: jfrog-values
      valuesKey: values.yaml
