---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: monitoring
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts
  insecure: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus-community
  namespace: monitoring
spec:
  targetNamespace: monitoring
  storageNamespace: monitoring
  releaseName: prometheus-community
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 12h
  values:
    prometheus:
      enabled: true
      prometheusSpec:
        # --- THIS IS THE SECTION TO CONFIGURE ---
        remoteWrite:
          - url: "http://10.96.235.11:8080/api/v1/write"
